### ISSUE TITLE
MatteAOV serialization

### ISSUE THREAD

**Issue by danbradham** [danbradham/mtoatools#1]
MatteAOVs should be portable across scenes that share geometry. Add MatteAOV model serialization/deserialization. Also add convenience methods for dumping/loading many MatteAOVs at once. 
# Serialization

``` python
aov = MatteAOV.create('matte')
aov.add('pCube1')
serialized = aov.yaml()
```

serialized is equivalent to the following yaml

``` yaml
name: "matte"
shapes:
    - name: pCubeShape1
      color: [1, 1, 1]
```
# Deserialization

``` python
aov = MatteAOV.load(serialized)
```
# Multi-seralization

``` python
save_mattes(mattes, filepath)
load_mattes(filepath)
```
